server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      
info:
  app:
    name: BookService
    description: This is a book service
    version: 1.0.0